import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a sidebar manually
  tutorialSidebar: [
    'intro',
    'why-physical-ai-matters',
    'learning-outcomes',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
      },
      items: [
        'module1/ros2-nodes-topics-services',
        'module1/bridging-python-agents-to-ros2',
        'module1/urdf-for-humanoids',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
       link: {
        type: 'generated-index',
      },
      items: [
        'module-2/simulating-physics-in-gazebo',
        'module-2/high-fidelity-rendering-in-unity',
        'module-2/simulating-sensors-lidar-depth-imu',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
       link: {
        type: 'generated-index',
      },
      items: [
        'module-3/isaac-sim-synthetic-data',
        'module-3/isaac-ros-vslam-navigation',
        'module-3/nav2-bipedal-path-planning',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
       link: {
        type: 'generated-index',
      },
      items: [
        'module-4/voice-to-action-whisper',
        'module-4/cognitive-planning-llm-to-ros2',
        'module-4/capstone-project-autonomous-humanoid',
      ],
    },
    'weekly-breakdown',
    'assessments',
    'hardware-requirements',
  ],
};

export default sidebars;
